export interface ScheduleActivityData {
  activity_code: string;
  description: string;
  discipline: string;
  line: string | null;
  location: string | null;
  planned_start: string;
  planned_end: string;
}

export interface HistoricalSeedRecord {
  project_name: string;
  discipline: string;
  activity_description: string;
  planned_duration_days: number;
  actual_duration_days: number;
  delay_cause: string | null;
  notes: string;
}

export const BASELINE_SCHEDULE: ScheduleActivityData[] = [
  { activity_code: 'L6-PIP-0241', description: 'Erect Line 24-XX', discipline: 'Piping', line: '24', location: 'Tank Farm', planned_start: '2026-08-01', planned_end: '2026-08-10' },
  { activity_code: 'L6-PIP-0242', description: 'Erect Line 25-XX', discipline: 'Piping', line: '25', location: 'Tank Farm', planned_start: '2026-08-05', planned_end: '2026-08-15' },
  { activity_code: 'L6-PIP-0189', description: 'Hydrotest Line 24-XX', discipline: 'Piping', line: '24', location: 'Tank Farm', planned_start: '2026-08-11', planned_end: '2026-08-14' },
  { activity_code: 'L6-CIV-0112', description: 'Construct Tank Farm Foundation', discipline: 'Civil', line: null, location: 'Tank Farm', planned_start: '2026-07-01', planned_end: '2026-07-25' },
  { activity_code: 'L6-CIV-0113', description: 'Backfill Foundation Area B', discipline: 'Civil', line: null, location: 'Tank Farm', planned_start: '2026-07-20', planned_end: '2026-07-28' },
  { activity_code: 'L6-ELE-0301', description: 'Install Cable Tray Section 4', discipline: 'Electrical', line: null, location: 'Substation', planned_start: '2026-08-02', planned_end: '2026-08-06' },
  { activity_code: 'L6-ELE-0302', description: 'Terminate Power Cables Panel B', discipline: 'Electrical', line: null, location: 'Substation', planned_start: '2026-08-07', planned_end: '2026-08-09' },
  { activity_code: 'L6-INS-0410', description: 'Install Pressure Transmitter PT-204', discipline: 'Instrumentation', line: '24', location: 'Tank Farm', planned_start: '2026-08-12', planned_end: '2026-08-13' },
  { activity_code: 'L6-INS-0411', description: 'Calibrate Flow Meter FM-118', discipline: 'Instrumentation', line: '18', location: 'Tank Farm', planned_start: '2026-08-14', planned_end: '2026-08-15' },
  { activity_code: 'L6-STE-0501', description: 'Align Pump Skid P-101', discipline: 'Static/Rotating', line: null, location: 'Pump House', planned_start: '2026-08-03', planned_end: '2026-08-05' },
  { activity_code: 'L6-STE-0502', description: 'Install Coupling Guard P-101', discipline: 'Static/Rotating', line: null, location: 'Pump House', planned_start: '2026-08-06', planned_end: '2026-08-06' },
  { activity_code: 'L6-HSE-0601', description: 'Conduct Confined Space Safety Audit', discipline: 'HSE', line: null, location: 'Tank Farm', planned_start: '2026-08-01', planned_end: '2026-08-01' },
  { activity_code: 'L6-PIP-0243', description: 'Weld Line 24-XX Spool Joints', discipline: 'Piping', line: '24', location: 'Tank Farm', planned_start: '2026-08-02', planned_end: '2026-08-04' },
  { activity_code: 'L6-PIP-0250', description: 'Erect Line 30-XX', discipline: 'Piping', line: '30', location: 'Pump House', planned_start: '2026-08-08', planned_end: '2026-08-16' },
  { activity_code: 'L6-CIV-0120', description: 'Pour Concrete Pedestal C-12', discipline: 'Civil', line: null, location: 'Pump House', planned_start: '2026-07-28', planned_end: '2026-08-01' },
];

export const HISTORICAL_DATASET: HistoricalSeedRecord[] = [
  {
    project_name: 'Duliajan Phase 2 Expansion',
    discipline: 'piping',
    activity_description: 'Erect 24-inch crude header spools at Tank Farm 3',
    planned_duration_days: 14,
    actual_duration_days: 26,
    delay_cause: 'material shortage',
    notes: 'Severe delay caused by non-delivery of ASTM A106 Grade B pipe fittings and 300# flanges from the regional vendor. Spool fabrication was halted for 12 days awaiting materials.',
  },
  {
    project_name: 'Jorhat Pipeline Expansion',
    discipline: 'piping',
    activity_description: 'Install stainless steel 316L bypass spools on Line 18',
    planned_duration_days: 8,
    actual_duration_days: 18,
    delay_cause: 'material shortage',
    notes: 'Specialty high-pressure stainless steel seamless spools were delayed at port customs. Crew had to be reassigned to secondary pipe rack supports while awaiting delivery.',
  },
  {
    project_name: 'Numaligarh Offsite Piping Project',
    discipline: 'piping',
    activity_description: 'Fit-up and weld carbon steel manifold lines 12-CS-04',
    planned_duration_days: 10,
    actual_duration_days: 19,
    delay_cause: 'material shortage',
    notes: 'Shortage of approved low-temperature carbon steel welding filler consumables and matching blind flanges delayed manifold fit-up by 9 days.',
  },
  {
    project_name: 'Digboi Refinery Modernization',
    discipline: 'piping',
    activity_description: 'Fabricate and erect condensate drain lines on Unit 400',
    planned_duration_days: 7,
    actual_duration_days: 14,
    delay_cause: 'material shortage',
    notes: 'Vendor delivered incorrect schedule 80 wall-thickness elbows instead of schedule 160. Work was paused until emergency air shipment of correct piping materials arrived.',
  },
  {
    project_name: 'Moran Gas Gathering Station Upgrade',
    discipline: 'piping',
    activity_description: 'Install high-pressure gas injection piping spools',
    planned_duration_days: 12,
    actual_duration_days: 22,
    delay_cause: 'material shortage',
    notes: 'Critical path delay due to lead-time failure on cryogenic ball valves and Class 600 gasket sets. Piping contractor could not close tie-in spools without valves.',
  },
  {
    project_name: 'Duliajan Phase 2 Expansion',
    discipline: 'piping',
    activity_description: 'Lay underground firewater ring main piping Section C',
    planned_duration_days: 20,
    actual_duration_days: 31,
    delay_cause: 'material shortage',
    notes: 'Batch manufacturing defects in factory-applied 3LPE external coating required rejecting 400m of ductile iron pipes. Waiting for re-coated pipe shipment created an 11-day delay.',
  },
  {
    project_name: 'Jorhat Pipeline Expansion',
    discipline: 'piping',
    activity_description: 'Erect overhead pipe rack spools across Area 3 corridor',
    planned_duration_days: 15,
    actual_duration_days: 24,
    delay_cause: 'preceding civil delay',
    notes: 'Piping erection crew could not access the corridor because the civil contractor had not completed concrete anchor pedastals and structural steel column grouting.',
  },
  {
    project_name: 'Digboi Refinery Modernization',
    discipline: 'piping',
    activity_description: 'Tie-in interconnecting utility piping to main compressor shelter',
    planned_duration_days: 9,
    actual_duration_days: 16,
    delay_cause: 'preceding civil delay',
    notes: 'Civil handover of the compressor equipment pit was 7 days behind schedule due to water ingress in unbackfilled trenches. Piping alignment was forced to wait.',
  },
  {
    project_name: 'Duliajan Phase 2 Expansion',
    discipline: 'static/rotating',
    activity_description: 'Position and align heavy feed pump skids P-101A/B',
    planned_duration_days: 6,
    actual_duration_days: 13,
    delay_cause: 'preceding civil delay',
    notes: 'Pump foundation concrete did not achieve 28-day target compressive strength on time. Skid placement was halted to prevent micro-cracking of the foundation block.',
  },
  {
    project_name: 'Moran Gas Gathering Station Upgrade',
    discipline: 'piping',
    activity_description: 'Install separator inlet piping and valve manifold',
    planned_duration_days: 11,
    actual_duration_days: 18,
    delay_cause: 'preceding civil delay',
    notes: 'Civil anchor bolts were embedded with 25mm misalignment on the vessel saddle support, requiring 7 days of structural chipping, rebar verification, and epoxy re-grouting.',
  },
  {
    project_name: 'Numaligarh Offsite Piping Project',
    discipline: 'piping',
    activity_description: 'Hydrostatic pressure test of fuel oil line 16-FO-01',
    planned_duration_days: 5,
    actual_duration_days: 7,
    delay_cause: 'permit/inspection hold',
    notes: 'Minor 2-day hold while third-party inspection agency (TPI) verified pressure chart recorder calibration certificates before approving test pressurization.',
  },
  {
    project_name: 'Jorhat Pipeline Expansion',
    discipline: 'piping',
    activity_description: 'Apply wrap insulation and cladding to hot steam tracer lines',
    planned_duration_days: 8,
    actual_duration_days: 9,
    delay_cause: 'weather',
    notes: 'Unseasonal heavy monsoon downpour prevented fiberglass insulation application for 1 day to avoid moisture entrapment.',
  },
  {
    project_name: 'Duliajan Phase 2 Expansion',
    discipline: 'piping',
    activity_description: 'Weld and NDT 100% radiography on Line 24 field joints',
    planned_duration_days: 10,
    actual_duration_days: 10,
    delay_cause: null,
    notes: 'Completed exactly on schedule. Zero weld repairs required on all 42 butt welds; RT inspection cleared on first pass.',
  },
  {
    project_name: 'Digboi Refinery Modernization',
    discipline: 'piping',
    activity_description: 'Golden tie-in weld execution during scheduled plant shutdown',
    planned_duration_days: 3,
    actual_duration_days: 3,
    delay_cause: null,
    notes: 'Night shift hot-tap and golden weld completed within the 72-hour turnaround window with full safety clearance.',
  },
  {
    project_name: 'Duliajan Phase 2 Expansion',
    discipline: 'civil',
    activity_description: 'Deep excavation and sheet piling for crude tank foundation TK-02',
    planned_duration_days: 21,
    actual_duration_days: 29,
    delay_cause: 'weather',
    notes: 'Heavy monsoon rains flooded the 4m excavation pit. Required continuous high-capacity dewatering pumps and soil re-compaction testing before raft rebar placement.',
  },
  {
    project_name: 'Jorhat Pipeline Expansion',
    discipline: 'civil',
    activity_description: 'Construct reinforced concrete bund wall around storage area',
    planned_duration_days: 14,
    actual_duration_days: 15,
    delay_cause: 'minor labor shortage',
    notes: 'Shuttering carpenter sub-contractor experienced high festival absenteeism; resolved within 24 hours by mobilizing standby crew.',
  },
  {
    project_name: 'Numaligarh Offsite Piping Project',
    discipline: 'civil',
    activity_description: 'Pour mass concrete slab for substructure Area B',
    planned_duration_days: 10,
    actual_duration_days: 10,
    delay_cause: null,
    notes: 'Continuous RMC pour executed smoothly over 36 hours. Curing blankets installed immediately; compressive strength tests met specification.',
  },
  {
    project_name: 'Moran Gas Gathering Station Upgrade',
    discipline: 'civil',
    activity_description: 'Cast-in-situ concrete pipe sleeper foundations along corridor',
    planned_duration_days: 18,
    actual_duration_days: 20,
    delay_cause: 'permit/inspection hold',
    notes: 'Encountered unmapped existing buried telecom cable during manual trial trenching. Work paused 2 days for utility clearance.',
  },
  {
    project_name: 'Digboi Refinery Modernization',
    discipline: 'civil',
    activity_description: 'Paving and storm water drainage channels around pump house',
    planned_duration_days: 12,
    actual_duration_days: 12,
    delay_cause: null,
    notes: 'Slope grading and precast drain covers installed on schedule with zero quality non-conformance.',
  },
  {
    project_name: 'Duliajan Phase 2 Expansion',
    discipline: 'civil',
    activity_description: 'Backfill and compaction around foundation Area B',
    planned_duration_days: 8,
    actual_duration_days: 8,
    delay_cause: null,
    notes: 'Completed in 250mm compacted layers with nuclear density testing confirming 98% Proctor density on each lift.',
  },
  {
    project_name: 'Duliajan Phase 2 Expansion',
    discipline: 'electrical',
    activity_description: 'Install heavy cable tray network in Substation 2',
    planned_duration_days: 10,
    actual_duration_days: 16,
    delay_cause: 'material shortage',
    notes: 'Perforated hot-dip galvanized cable tray bends and heavy-duty unistrut brackets were under-shipped by supplier, causing a 6-day installation halt.',
  },
  {
    project_name: 'Jorhat Pipeline Expansion',
    discipline: 'electrical',
    activity_description: 'Pull 11kV medium voltage power feeder cables from Grid SS',
    planned_duration_days: 12,
    actual_duration_days: 14,
    delay_cause: 'contractor manpower shortage',
    notes: 'Specialized cable pulling winch crew was delayed on an adjoining gas plant shutdown, causing a 2-day start lag.',
  },
  {
    project_name: 'Digboi Refinery Modernization',
    discipline: 'electrical',
    activity_description: 'Install and terminate 415V motor control center (MCC) panels',
    planned_duration_days: 9,
    actual_duration_days: 9,
    delay_cause: null,
    notes: 'Busbar torque verification and hi-pot dielectric insulation testing completed flawlessly on schedule.',
  },
  {
    project_name: 'Numaligarh Offsite Piping Project',
    discipline: 'electrical',
    activity_description: 'Install explosion-proof plant perimeter lighting and earthing grid',
    planned_duration_days: 15,
    actual_duration_days: 16,
    delay_cause: 'weather',
    notes: 'Exothermic weld earthing connections delayed by 1 day due to surface moisture and light rain.',
  },
  {
    project_name: 'Moran Gas Gathering Station Upgrade',
    discipline: 'electrical',
    activity_description: 'Commission emergency diesel generator (EDG) automatic transfer switch',
    planned_duration_days: 5,
    actual_duration_days: 5,
    delay_cause: null,
    notes: 'Full load test and blackout simulation successfully triggered transfer switch in 6.2 seconds, well within specification.',
  },
  {
    project_name: 'Duliajan Phase 2 Expansion',
    discipline: 'instrumentation',
    activity_description: 'Install radar tank gauging transmitters and remote telemetry',
    planned_duration_days: 7,
    actual_duration_days: 13,
    delay_cause: 'material shortage',
    notes: 'Custom HART-compatible guided wave radar sensor antennas were delayed during international freight transit for 6 days.',
  },
  {
    project_name: 'Jorhat Pipeline Expansion',
    discipline: 'instrumentation',
    activity_description: 'Run stainless steel instrument impulse tubing for orifice meters',
    planned_duration_days: 8,
    actual_duration_days: 9,
    delay_cause: 'permit/inspection hold',
    notes: 'Nitrogen leak test signoff delayed 1 day awaiting client instrumentation engineer counter-signature.',
  },
  {
    project_name: 'Digboi Refinery Modernization',
    discipline: 'instrumentation',
    activity_description: 'Loop check and calibration of automated emergency shutdown valves (ESDVs)',
    planned_duration_days: 6,
    actual_duration_days: 6,
    delay_cause: null,
    notes: 'All 18 ESDVs verified for full stroke time (<2.5 sec) and smart positioner feedback loop integrity.',
  },
  {
    project_name: 'Numaligarh Offsite Piping Project',
    discipline: 'instrumentation',
    activity_description: 'Install distributed control system (DCS) Marshalling Cabinets',
    planned_duration_days: 10,
    actual_duration_days: 12,
    delay_cause: 'preceding civil delay',
    notes: 'HVAC positive-pressure clean air conditioning in the central control room was not commissioned on time, delaying electronic cabinet uncrating.',
  },
  {
    project_name: 'Moran Gas Gathering Station Upgrade',
    discipline: 'instrumentation',
    activity_description: 'Deploy ultrasonic gas flow meters on sales metering skid',
    planned_duration_days: 5,
    actual_duration_days: 5,
    delay_cause: null,
    notes: 'Calibration certificates validated; zero-flow noise verification test passed on first attempt.',
  },
  {
    project_name: 'Duliajan Phase 2 Expansion',
    discipline: 'static/rotating',
    activity_description: 'Erect vertical hydrocarbon separator column C-102',
    planned_duration_days: 8,
    actual_duration_days: 10,
    delay_cause: 'weather',
    notes: 'Heavy wind gusting above 35 knots exceeded maximum crane safety limits for tandem heavy lift on day 3, delaying column rigging.',
  },
  {
    project_name: 'Jorhat Pipeline Expansion',
    discipline: 'static/rotating',
    activity_description: 'Align and grout multistage crude booster pump P-201',
    planned_duration_days: 6,
    actual_duration_days: 11,
    delay_cause: 'material shortage',
    notes: 'Missing precision stainless steel shim sets and API-compliant mechanical seal spare kits held up final shaft laser alignment for 5 days.',
  },
  {
    project_name: 'Digboi Refinery Modernization',
    discipline: 'static/rotating',
    activity_description: 'Install internal distillation trays in Fractionation Column',
    planned_duration_days: 14,
    actual_duration_days: 14,
    delay_cause: null,
    notes: 'Clean room protocol observed; all 36 bubble cap trays levelled within 1mm tolerance with full QA signoff.',
  },
  {
    project_name: 'Numaligarh Offsite Piping Project',
    discipline: 'static/rotating',
    activity_description: 'Hydrotest and box-up of shell-and-tube heat exchanger E-104',
    planned_duration_days: 7,
    actual_duration_days: 8,
    delay_cause: 'permit/inspection hold',
    notes: 'Channel cover gasket seating inspection required re-torquing and 24-hour hold verification.',
  },
  {
    project_name: 'Moran Gas Gathering Station Upgrade',
    discipline: 'static/rotating',
    activity_description: 'Perform laser optical shaft alignment on gas compressor skid K-301',
    planned_duration_days: 5,
    actual_duration_days: 5,
    delay_cause: null,
    notes: 'Cold and hot alignment offsets achieved within 0.03mm radial and axial runout specification.',
  },
  {
    project_name: 'Duliajan Phase 2 Expansion',
    discipline: 'hse',
    activity_description: 'Commission plant optical flame and toxic gas detection system',
    planned_duration_days: 6,
    actual_duration_days: 6,
    delay_cause: null,
    notes: 'All 32 infrared flame detectors and hydrogen sulfide sensors bump-tested; executive shutdown voting logic verified.',
  },
  {
    project_name: 'Jorhat Pipeline Expansion',
    discipline: 'hse',
    activity_description: 'Full-flow discharge test of deluge foam suppression system on Tank 01',
    planned_duration_days: 4,
    actual_duration_days: 5,
    delay_cause: 'minor equipment adjustment',
    notes: 'Proportioner foam ratio calibrated on second run to achieve exact 3% aqueous film-forming foam (AFFF) mixture.',
  },
  {
    project_name: 'Digboi Refinery Modernization',
    discipline: 'hse',
    activity_description: 'Install safety shower and eye wash emergency stations along units',
    planned_duration_days: 5,
    actual_duration_days: 5,
    delay_cause: null,
    notes: 'Potable water pressure and tepid temperature blending valves commissioned across all 8 field safety stations.',
  },
  {
    project_name: 'Numaligarh Offsite Piping Project',
    discipline: 'hse',
    activity_description: 'Pre-startup safety review (PSSR) walkthrough and punch list closure',
    planned_duration_days: 7,
    actual_duration_days: 8,
    delay_cause: 'inspection punch closure',
    notes: 'Cat B safety signboards and valve tagging completed prior to hydrocarbon introduction.',
  },
  {
    project_name: 'Moran Gas Gathering Station Upgrade',
    discipline: 'hse',
    activity_description: 'Erect blast wall safety barriers adjacent to control building',
    planned_duration_days: 10,
    actual_duration_days: 10,
    delay_cause: null,
    notes: 'Pre-stressed reinforced blast panels anchored and certified for 0.5 bar overpressure resistance.',
  },
];
